name: RubidiaSecretPaths
version: 2.0
api-version: 1.13
main: me.pmilon.RubidiaSecretPaths.SecretPathsManager
author: Rubilmax
depend: [WorldEdit, RubidiaCore]
commands:
  portal:
    description: Creates a portal with your worldedit selection.