name: RubidiaManager
author: pmilon
version: 1.0
description: The Manager plugin of Rubidias server.
main: me.pmilon.RubidiaManager.RubidiaManagerPlugin
softdepend: [RubidiaCore, RubidiaGuilds, EffectLib, WorldEdit, Multiverse-Core]
commands:
  chunk:
    description: Chunk management.
    aliases: c
  chunks:
    description: Chunks management.
    aliases: chs