abilities:
  PALADIN:
    '1':
      name: Charge-Charge
      description:
      - The Paladin charges straight
      - in front of him with his complete
      - body until he reaches something.
      - Le Paladin fonce droit devant
      - lui jusqu'à ce qu'il rencontre
      - un obstacle, qu'il explosera.
      passive: false
      sequence: DGG,SP
      levelMax: 30
      vigorMin: 13
      vigorPerLevel: 0.82
      damagesMin: 1.7
      damagesPerLevel: 0.22
      mastery: ADVENTURER
    '2':
      name: Fatal Blow-Coup fatal
      description:
      - The Paladin jumps ~5 blocks high
      - then strike down the ground.
      - Le Paladin saute de ~5 blocs pour
      - pour frapper le sol de toute sa force.
      passive: false
      sequence: DGD,SN
      levelMax: 30
      vigorMin: 15
      vigorPerLevel: 1.09
      damagesMin: 2.05
      damagesPerLevel: 0.26
      mastery: ADVENTURER
    '3':
      name: Furie-Furie
      description:
      - The Paladin has a passive unearthly
      - strength granted by the Knight's Guild
      - for his unbelievable bravour.
      - Le Paladin possède une force surnaturelle,
      - que la Confrérie des Chevaliers lui
      - octroie pour sa bravoure exceptionnelle.
      passive: true
      sequence: ''
      levelMax: 40
      vigorMin: 0.0
      vigorPerLevel: 0.0
      damagesMin: 0.0
      damagesPerLevel: 0.4325
      mastery: ADVENTURER
      unit: '%-%'
    '4':
      name: Iron Skin-Peau de fer
      description:
      - The Paladin has got a hardened skin
      - given by the Lord of Mearwood for
      - having formerly saved Rubidia's countries.
      - Le Paladin possède une peau renforcée
      - offerte par le Roi de Mearwood pour avoir
      - autrefois sauvé les contrées de Rubidia.
      passive: true
      sequence: ''
      levelMax: 30
      vigorMin: 0.0
      vigorPerLevel: 0.0
      damagesMin: 0.0
      damagesPerLevel: 0.5
      mastery: ADVENTURER
      unit: '%-%'
      suppInfo: Defense-Défense
    '5':
      name: Blades Spin-Danse de Lames
      description:
      - The Paladin starts spinning at an
      - incredible speed, causing heavy
      - damages to everyone meeting his axes.
      - Le Paladin entraîne ses haches dans une virevolte
      - très rapide, causant de lourds dommages
      - à tous les ennemis rencontrant ses lames.
      passive: false
      sequence: DDD,SN
      levelMax: 30
      vigorMin: 19
      vigorPerLevel: 1.32
      damagesMin: 2.6
      damagesPerLevel: 0.36
      mastery: MASTER
    '6':
      name: Berserker Rage-Rage du Berserker
      description:
      - The Paladin enters in a powerful
      - rage that increase his speed,
      - strength and damage resistance.
      - Le Paladin entre dans une frénésie
      - qui lui permet d'augmenter sa vitesse,
      - sa force et sa résistance aux dégâts.
      passive: false
      sequence: DDD,!SN
      levelMax: 20
      vigorMin: 18
      vigorPerLevel: -0.6
      damagesMin: 0.0
      damagesPerLevel: 0.0
      mastery: MASTER
      toggleable: true
    '7':
      name: Meta Fusion-Meta Fusion
      description:
      - The Paladin starts to concentrate
      - for 2 seconds, taking reduced damages
      - after which he releases his full energy.
      - Le Paladin concentre sa force durant
      - 2 secondes subissant des dégâts reduits,
      - après lesquelles il relâche toute son énergie.
      passive: false
      sequence: DGG,SN
      levelMax: 20
      vigorMin: 26
      vigorPerLevel: 1.8
      damagesMin: 2.95
      damagesPerLevel: 0.68
      mastery: HERO
    '8':
      name: Ground Smash-Frappe du Golem
      description:
      - The Paladin heavily smashes the ground
      - causing enemies around, once
      - pushed in the air, to get sprayed.
      - Le Paladin frappe lourdement le sol
      - causant les ennemis alentours, une fois
      - dans les airs, à être pulvérisés.
      passive: false
      sequence: GDD,SN
      levelMax: 30
      vigorMin: 31
      vigorPerLevel: 1.26
      damagesMin: 3.2
      damagesPerLevel: 0.41
      mastery: HERO
  RANGER:
    '1':
      name: Salve-Salve
      description:
      - The Ranger launches loads of
      - arrows in a very short time.
      - La Ranger lance une grande quantité
      - de flèches en un court laps de temps.
      passive: false
      sequence: GDG,SN
      levelMax: 20
      vigorMin: 11
      vigorPerLevel: 0.9
      damagesMin: 3.0
      damagesPerLevel: 0.65
      mastery: ADVENTURER
      suppInfo: Arrows-Flèches
    '2':
      name: Explosive Arrow-Flèche Explosive
      description:
      - The Ranger launches an Arrow which explode
      - in contact with something, just after having
      - delivered a message to the surroundings.
      - Le Ranger lance une flèche explosant
      - au contact, un bref moment après avoir
      - délivré un message aux alentours.
      passive: false
      sequence: DGD,SN
      levelMax: 30
      vigorMin: 17
      vigorPerLevel: 0.96
      damagesMin: 1.3
      damagesPerLevel: 0.41
      mastery: ADVENTURER
    '3':
      name: Poison Arrows-Flèches Empoisonnées
      description:
      - The Arrows of the Ranger are all
      - bathed in an Arsenic-based solution,
      - causing damages in time after impact.
      - Les flèches du Ranger sont toutes
      - trempées dans une solution d'Arsenic,
      - causant à l'impact des dégâts dans le temps.
      passive: true
      sequence: ''
      levelMax: 40
      vigorMin: 0.0
      vigorPerLevel: 0.0
      damagesMin: 0.0
      damagesPerLevel: 0.06
      mastery: ADVENTURER
      suppInfo: Effect duration-Durée de l'effet
      unit: sec-sec
    '4':
      name: Fire Arrows-Flèches de Feu
      description:
      - The Arrows of the Ranger are all covered of a
      - little powder that ignites in contact with the skin.
      - Les Flèches du Ranger sont couvertes d'une
      - poudre qui s'enflamme au contact de la peau.
      passive: true
      sequence: ''
      levelMax: 40
      vigorMin: 0.0
      vigorPerLevel: 0.0
      damagesMin: 0.0
      damagesPerLevel: 0.25
      mastery: ADVENTURER
      suppInfo: Effect duration-Durée de l'effet
      unit: sec-sec
    '5':
      name: Sniper Shot-Tir de Précision
      description:
      - The Ranger increases his accuracy
      - for 3 seconds after what he shots
      - an unbelievable powerful and very fast arrow.
      - Le Ranger augmente sa précision durant 3
      - secondes, après lesquelles il décoche une
      - flèche incroyablement puissante et très rapide.
      passive: false
      sequence: DGG,SN
      levelMax: 30
      vigorMin: 34
      vigorPerLevel: 1.32
      damagesMin: 4.0
      damagesPerLevel: 1.36
      mastery: MASTER
    '6':
      name: Raining Arrows-Pluie de Flèches
      description:
      - The Ranger shots lots of arrows
      - above his targetted enemy, to create
      - a little random rain of arrows.
      - Le Ranger décoche des flèches
      - au dessus de la cible, créant une
      - petite pluie aléatoire et violente.
      passive: false
      sequence: GDD,SN
      levelMax: 20
      vigorMin: 29
      vigorPerLevel: 1.46
      damagesMin: 5.0
      damagesPerLevel: 1.25
      mastery: MASTER
    '7':
      name: Aiming Arrow-Flèche Chercheuse
      description:
      - The Ranger puts all of his energy into
      - this strong arrow, allowing it to follow
      - the nearest targetted enemy.
      - Le Ranger rassemble tous ses pouvoirs dans
      - cette puissante flèche, lui permettant de
      - suivre l'ennemi ciblé le plus proche.
      passive: false
      sequence: DDD,SN
      levelMax: 20
      vigorMin: 29
      vigorPerLevel: 1.46
      damagesMin: 2.55
      damagesPerLevel: 0.76
      mastery: HERO
    '8':
      name: Legendary Arrow-Flèche Légendaire
      description:
      - The Ranger concentrate his agility
      - into his next valid arrow, devastating
      - its target in a legendary way.
      - Le Ranger concentre son agilité
      - dans sa prochaine flèche valide,
      - pulvérisant sa cible légendairement.
      passive: false
      sequence: DDD,!SN
      levelMax: 30
      vigorMin: 36
      vigorPerLevel: 1.16
      damagesMin: 3.4
      damagesPerLevel: 0.57
      mastery: HERO
  MAGE:
    '1':
      name: Fireball Rain-Pluie de Météores
      description:
      - The Mage creates a random rain of
      - meteors above the target, causing
      - environmental and zone damages
      - Le Mage crée une pluie aléatoire de
      - météores au dessus de la cible, causant
      - des dégâts de zone et environnementaux.
      passive: false
      sequence: DGG,!SN
      levelMax: 30
      vigorMin: 14
      vigorPerLevel: 0.84
      damagesMin: 2.0
      damagesPerLevel: 0.5
      mastery: ADVENTURER
      suppInfo: Meteors-Météores
    '2':
      name: Circle of Death-Cercle de la Mort
      description:
      - The Mage invokes lightning's powers to make
      - them strike everything in his surroundings.
      - Le Mage invoque les pouvoirs des éclairs pour
      - les faire s'abattre sur les ennemis alentours.
      passive: false
      sequence: DGD,SN
      levelMax: 30
      vigorMin: 22
      vigorPerLevel: 0.81
      damagesMin: 1.78
      damagesPerLevel: 0.26
      mastery: ADVENTURER
    '3':
      name: Teleportation-Téléportation
      description:
      - The Mage bend space and time to
      - teleport himself where he's looking at.
      - Le Mage plie l'espace et le temps afin
      - de se téléporter là où il regarde.
      passive: false
      sequence: DDD,SP
      levelMax: 40
      vigorMin: 21
      vigorPerLevel: 0.79
      damagesMin: 2.0
      damagesPerLevel: 0.2
      mastery: ADVENTURER
      suppInfo: Range-Portée
      unit: blocks-blocs
    '4':
      name: Heal-Soin
      description:
      - The Mage is able to heal himself and his
      - allies in a short area and a brief time.
      - Le Mage est capable de se soigner
      - immédiatement lui et ses alliés proches.
      passive: false
      sequence: DDD,SN
      levelMax: 30
      vigorMin: 24
      vigorPerLevel: 1.12
      damagesMin: 2.0
      damagesPerLevel: 0.48
      mastery: ADVENTURER
      suppInfo: Heal Amount-Vie Restaurée
      unit: HP-PV
    '5':
      name: Frozen Wind-Vent Glacé
      description:
      - The Mage creates a powerful frozen wind
      - that freezes and slows every enemies
      - it touches and causing light damages.
      - Le Mage façonne un vent glacé puissant
      - ralentissant les ennemis touchés
      - et causant de légers dégâts.
      passive: false
      sequence: DGG,SN
      levelMax: 30
      vigorMin: 29
      vigorPerLevel: 0.88
      damagesMin: 1.15
      damagesPerLevel: 0.18
      mastery: MASTER
    '6':
      name: Kynesis Handling-Kinésietechnie
      description:
      - The Mage masters kinesis powers, allowing
      - him to spread nearby enemies in the
      - surrounding area, equally damaging them.
      - Le Mage maîtrise les pouvoirs kinétiques, lui
      - permettant de propager les ennemis proches dans
      - une zone alentour, tout en infligeant des dégâts.
      passive: false
      sequence: GDD,SN
      levelMax: 20
      vigorMin: 37
      vigorPerLevel: 1.04
      damagesMin: 2.35
      damagesPerLevel: 0.69
      mastery: MASTER
    '7':
      name: Nether Army-Armée du Nether
      description:
      - The Mage invokes an army of minions from
      - the underworld that will help him
      - in fight for a certain amount of time.
      - Le Mage invoque une armée de
      - minions des enfers qui l'aidera en
      - combat pendant un certain temps.
      passive: false
      sequence: DDG
      levelMax: 20
      vigorMin: 28
      vigorPerLevel: 1.88
      damagesMin: 1.0
      damagesPerLevel: 0.45
      mastery: HERO
      suppInfo: Minions-Minions
    '8':
      name: Armageddon-Armageddon
      description:
      - The Mage creates a circle of fire around him
      - before everythings get deflagrated, causing
      - Zone and environnemental damages.
      - Le Mage crée un cercle de feu autour de lui
      - avant que tout ne soit dévasté, causant
      - dégats de zone et environnementaux.
      passive: false
      sequence: DDD,!SN!SP
      levelMax: 30
      vigorMin: 41
      vigorPerLevel: 1.19
      damagesMin: 3.4
      damagesPerLevel: 0.57
      mastery: HERO
  ASSASSIN:
    '1':
      name: Furtive Attack-Attaque Furtive
      description:
      - The Assassin moves really fast towards
      - the targetted enemy, disappearing
      - and reappearing behind his back.
      - L'Assassin transperce l'ennemi cible
      - extrêmement rapidement, donnant
      - l'illusion de s'être téléporté.
      passive: false
      sequence: DDG,!SN
      levelMax: 40
      vigorMin: 17
      vigorPerLevel: 0.64
      damagesMin: 1.5
      damagesPerLevel: 0.22
      mastery: ADVENTURER
    '2':
      name: Hyper Cloak-Camouflage
      description:
      - The Assassin is able to completely
      - disappear for a short time, even
      - equipped with a heavy armor.
      - L'Assassin est capable de se camoufler
      - entièrement durant un laps de temps,
      - même équipé d'une armure lourde.
      passive: false
      sequence: DDD,SN
      levelMax: 30
      vigorMin: 24
      vigorPerLevel: 0.83
      damagesMin: 3.0
      damagesPerLevel: 0.17
      mastery: ADVENTURER
      suppInfo: Duration-Durée
      unit: sec-sec
    '3':
      name: Flash Speed-Vitesse Flash
      description:
      - The Assassin is able to move really quick
      - so that nobody else can catch him up.
      - L'Assassin est capable de se déplacer
      - bien plus rapidement que quiconque.
      passive: true
      sequence: ''
      levelMax: 30
      vigorMin: 0.0
      vigorPerLevel: 0.0
      damagesMin: 100.0
      damagesPerLevel: 3.5
      mastery: ADVENTURER
      suppInfo: Speed-Vitesse
      unit: '%-%'
    '4':
      name: Evasion-Evasion
      description:
      - The Assassin can escape a fight
      - whenever he wants, by jumping
      - high and backward.
      - L'Assassin peut s'échapper
      - d'un combat lorsqu'il le veut en
      - sautant haut et en arrière.
      passive: false
      sequence: DGD,SN
      levelMax: 30
      vigorMin: 29
      vigorPerLevel: 1.01
      damagesMin: 0.8
      damagesPerLevel: 0.46
      mastery: ADVENTURER
    '5':
      name: Trap-Piège
      description:
      - The Assassin entwines his target so
      - that it cannot move for a short time.
      - L'Assassin enlace sa cible de sorte qu'elle
      - ne puisse bouger durant un certain temps.
      passive: false
      sequence: DDG,SN
      levelMax: 30
      vigorMin: 33
      vigorPerLevel: 0.77
      damagesMin: 1.0
      damagesPerLevel: 0.14
      mastery: MASTER
      suppInfo: Duration-Durée
      unit: sec-sec
    '6':
      name: Ninja Diversion-Diversion Ninja
      description:
      - The Assassin create a thick smoke
      - everywhere he's walking, causing
      - heavy damages to nearby enemies.
      - L'Assassin crée un épais nuage
      - blanc autour de lui, causant de
      - lourds dégâts aux ennemis proches.
      passive: false
      sequence: DDD,!SN
      levelMax: 20
      vigorMin: 6
      vigorPerLevel: 0.3
      damagesMin: 2.3
      damagesPerLevel: 0.17
      mastery: MASTER
      unit: / sec- / sec
      toggleable: true
    '7':
      name: Percing Attack-Attaque Perçante
      description:
      - The Assassin pierces his enemy
      - so violently that it gets projected
      - few blocks back.
      - L'Assassin traverse sa cible à une telle
      - allure qu'elle se retrouve projetée
      - à quelques blocs en arrière.
      passive: false
      sequence: GGD,SP
      levelMax: 20
      vigorMin: 38
      vigorPerLevel: 1.18
      damagesMin: 3.1
      damagesPerLevel: 0.72
      mastery: HERO
    '8':
      name: Super Smash-Super Smash
      description:
      - The Assassin dashes forward very
      - violently, forcing the target (if
      - existing) and him to take a huge flight.
      - L'Assassin dash très violemment
      - devant lui, forçant la cible (si
      - existante) et lui à faire un petit saut.
      passive: false
      sequence: DGD
      levelMax: 30
      vigorMin: 47
      vigorPerLevel: 1.08
      damagesMin: 3.9
      damagesPerLevel: 0.62
      mastery: HERO
saveconfigs: true
saveinterval: 900
announcements:
  - Aimez notre page facebook pour vous tenir au courant du développement du serveur et des éventuelles interventions !--http://www.facebook.com/RubidiaRPG
  - Inscrivez-vous sur notre site internet pour vous tenir au courant des mises à jour !--http://www.rubidia.xyz
  - Le statut VIP, les compagnons et d'autres trésors sont disponibles à l'achat dans la boutique du serveur !--http://www.rubidia.xyz/shop
  - N'hésitez pas à prendre une pause, elle ne peut que vous être bénéfique ! Profitez-en pour ouvrir votre boutique (/shop).
  - Vous pouvez visionner la cinématique de Mearwood.--http://youtu.be/QD9nPR8vBNE
  - Votez quotidiennement pour le serveur et remportez rubis, émeraudes et coffres chance !--http://www.rubidia.xyz/votes
  - Découvrez la véritable allure de Rubidia grâce aux textures activables dans le menu des préférences !
announcementsInterval: 20
badwords:
  - ntm
  - enculé
  - enculer
  - tg
  - ta gueule
  - ta geule
  - ta guele
  - connard
  - conard
  - pute
  - ta mer
  - tamer
  - ta mère
  - fdp
  - vtff
  - fils de
  - nique t
  - salope
  - salope
  - pétasse
  - connasse
  - conasse
  - ta chatte
  - ta chate
  - sale chien
  - pd